export const product_data = [
  {
    id: "1000000000",
    name: "Aaliyaaaaa",
    price: "1234 - 2345",
    category: "trolley",
    "sub-category": "fully",
    colors: ["Green", "Yellow", "Black"],
    sizes: ["M", "XL"],
    pricing: [
      {
        sku: "Aaliyaaaaa M Green",
        size: "M",
        color: "Green",
        price: 100,
        stock: 10,
      },
      {
        sku: "Aaliyaaaaa M Yellow",
        size: "M",
        color: "Yellow",
        price: 150,
        stock: 15,
      },
      {
        sku: "Aaliyaaaaa M Black",
        size: "M",
        color: "Black",
        price: 150,
        stock: 15,
      },
      {
        sku: "Aaliyaaaaa XL Green",
        size: "XL",
        color: "Green",
        price: 20,
        stock: 15,
      },
      {
        sku: "Aaliyaaaaa XL Yellow",
        size: "XL",
        color: "Yellow",
        price: 150,
        stock: 15,
      },
      {
        sku: "Aaliyaaaaa XL Black",
        size: "XL",
        color: "Black",
        price: 200,
        stock: 14,
      },
    ],
    description: "Something about product",
    images_path: ["/images/dress.svg", "/images/dress.png"],
    key_words: "",
    rating: 3.3,
  },
  {
    id: "1000000000",
    name: "Some other",
    price: "1234 - 2345",
    category: "trolley",
    "sub-category": "fully",
    colors: ["Green", "Yellow", "Black"],
    sizes: ["M", "XL"],
    pricing: [
      {
        sku: "Some other M Green",
        size: "M",
        color: "Green",
        price: 100,
        stock: 10,
      },
      {
        sku: "Some other M Yellow",
        size: "M",
        color: "Yellow",
        price: 150,
        stock: 15,
      },
      {
        sku: "Some other M Black",
        size: "M",
        color: "Black",
        price: 150,
        stock: 15,
      },
      {
        sku: "Some other XL Green",
        size: "XL",
        color: "Green",
        price: 20,
        stock: 15,
      },
      {
        sku: "Some other XL Yellow",
        size: "XL",
        color: "Yellow",
        price: 150,
        stock: 15,
      },
      {
        sku: "Some other XL Black",
        size: "XL",
        color: "Black",
        price: 200,
        stock: 14,
      },
    ],
    description: "Something about product",
    images_path: ["/images/dress1.jpeg", "/images/dress.png"],
    key_words: "",
    rating: 3,
  },
  {
    id: "1000000000",
    name: "Aaliya Slim",
    price: "1234 - 2345",
    category: "trolley",
    "sub-category": "fully",
    colors: ["Green", "Yellow", "Black"],
    sizes: ["M", "XL"],
    pricing: [
      {
        sku: "Aaliya Slim M Green",
        size: "M",
        color: "Green",
        price: 100,
        stock: 10,
      },
      {
        sku: "Aaliya Slim M Yellow",
        size: "M",
        color: "Yellow",
        price: 150,
        stock: 15,
      },
      {
        sku: "Aaliya Slim M Black",
        size: "M",
        color: "Black",
        price: 150,
        stock: 15,
      },
      {
        sku: "Aaliya Slim XL Green",
        size: "XL",
        color: "Green",
        price: 20,
        stock: 0,
      },
      {
        sku: "Aaliya Slim XL Yellow",
        size: "XL",
        color: "Yellow",
        price: 150,
        stock: 15,
      },
      {
        sku: "Aaliya Slim XL Black",
        size: "XL",
        color: "Black",
        price: 200,
        stock: 14,
      },
    ],
    description: "Something about product",
    images_path: ["/images/dress.jpeg", "/images/dress.png"],
    key_words: "",
    rating: 4.5,
  },
  {
    id: "1000000005",
    name: "Aaliya Long",
    price: "1250",
    category: "trolley",
    "sub-category": "fully",
    colors: ["Green"],
    sizes: ["M"],
    pricing: [
      {
        sku: "Aaliya Long M Green",
        size: "M",
        color: "Green",
        price: 100,
        stock: 10,
      },
    ],
    description: "Something about product",
    images_path: ["/images/dress2.jpeg", "/images/dress1.jpeg"],
    key_words: "",
    rating: 2,
  },
];
